name: Build and Test

on:
  push:
    branches: [ main ]

env:
  SCHEME: Studioframe
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 13,OS=16.0

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' -UseNewBuildSystem=NO build

  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Test
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' test


